#! /usr/bin/env mulle-bash
# shellcheck shell=bash


[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"


setup_test()
{
#   echo "**********************************************" >&2
#   echo "**********************************************" >&2
#   echo "**********************************************" >&2
#   echo "**********************************************" >&2
#   echo "**********************************************" >&2
#   env >&2
#   echo "**********************************************" >&2
#   echo "**********************************************" >&2
#   echo "**********************************************" >&2
#   echo "**********************************************" >&2
#   echo "**********************************************" >&2

   case "${PROJECT_DIALECT}" in
      c|objc)
         MULLE_VIRTUAL_ROOT="" exekutor mulle-sde ${MULLE_SDE_FLAGS} \
                                          ${MULLE_TECHNICAL_FLAGS} \
                                          init -d test \
                                          -r "mulle-sde/${PROJECT_DIALECT}-test" \
                                          none
      ;;

      "")
         fail "Empty PROJECT_DIALECT"
      ;;

      *)
         fail "Unsupported dialect \"${PROJECT_DIALECT}\""
      ;;
   esac
}


main()
{
   while [ $# -ne 0 ]
   do
      if options_technical_flags "$1"
      then
         shift
         continue
      fi

      case "$1" in
         --f)
            MULLE_FLAG_MAGNUM_FORCE='YES'
         ;;

         --marks)
            shift
         ;;

         -*)
            fail "unknown flag \"$1\""
         ;;
      esac

      shift
   done

   options_setup_trace "${MULLE_TRACE}" && set -x

   setup_test "$@"
}


main "$@"
