#! /usr/bin/env mulle-bash
# shellcheck shell=bash
#
#   Copyright (c) 2017 Nat! - Mulle kybernetiK
#   All rights reserved.
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions are met:
#
#   Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
#   Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
#   Neither the name of Mulle kybernetiK nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#   ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#   LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#   CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#   SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#   POSSIBILITY OF SUCH DAMAGE.
#
[ "${TRACE:-}" = "YES" -o "${MULLE_TEST_TRACE:-}" = "YES" ] && set -x && : "$0" "$@"


MULLE_EXECUTABLE_VERSION="6.6.2"

#
# Determine location of own libexec directory. Which is `src` in development
# and ../libexec when deployed. MULLE_EXECUTABLE needs to be defined for this.
#

if ! [ ${MULLE_TEST_LIBEXEC_DIR+x} ]
then
   r_get_libexec_dir "${MULLE_EXECUTABLE}" "mulle-test" "mulle-test-init.sh"
   MULLE_TEST_LIBEXEC_DIR="${RVAL}"
fi

# version is in mulle-test-env
set +u


test::usage()
{
   cat <<EOF >&2
Usage:
   ${MULLE_EXECUTABLE_NAME} [flags] <command> <options> -- <build> -- <run>

   Run tests. Commands take options. Some commands take additional build and
   run options. Notice the -- separator.

   Create your test environment with \`mulle-test init\`. Then build your
   test environment with \`mulle-test craft\`. Now you can run the tests with
   \`mulle-test run\`.

   To iterate over a test "foo.c" and library code until you get it right,
   use \`mulle-test --no-clean crun foo.c\`. This will build changes to
   the library and then recompile and run the test.

   mulle-test can generate coverage information and supports various sanitizers
   such as valgrind (see Flags)

   Test with different architecture:
      mulle-sde test clean all
      mulle-sde -DCFLAGS=-m32 test craft
      mulle-sde -DMULLE_ARCH=i686 -DCFLAGS=-m32 test run sizeof.c

Flags:
EOF

   (
      options_technical_flags_usage "                   : "
      cat <<EOF
   --dir-name <name>       : specify test directory name (default: test)
   --no-sanitizer          : no sanitizer
   --no-clean              : do not clean before crafting
   --coverage              : produce clang coverage information
   --gdb                   : use gdb to run
   --objc-coverage         : produce mulle-objc coverage information
   --sanitize-address      : use address sanitizer to craft and run
   --sanitize-thread       : use thread sanitizer to craft and run
   --sanitize-undefined    : use undefined sanitizer to craft and run
   --testallocator         : use mulle-testallocator to run (default)
   --valgrind              : use valgrind to run
   --valgrind-no-leaks     : use valgrind without leak checker run
   --zombie                : use zombie sanitizer
EOF
   ) | sort >&2


   cat <<EOF >&2

Commands:
   arch                    : name of current architecture
   clean                   : remove dependency, kitchens and exe files
   craft                   : force rebuild of project, then run tests
   init                    : setup a test project for the current project
   recraft                 : clean all, then craft
   crun                    : craft library if needed, then run a single test
   run                     : run tests, crafts beforehand if needed
   rerun                   : run failing tests again
   test-dir                : locate test folder

Environment:
   MULLE_TEST_DIR          : tests directory (test)
   MULLE_TEST_OBJC_DIALECT : use mulle-objc for mulle-clang
   PROJECT_DIALECT         : dialect of the tests, can be objc
   PROJECT_EXTENSIONS      : file extensions of the test files
   PROJECT_LANGUAGE        : language of the tests (c)
   TEST_PROJECT_NAME       : name of the "parent" project that gets tested

EOF

   exit 1
}


#
# 0 OK
# 4 its a script
#
test::cd_test_dir()
{
   log_entry "test::cd_test_dir" "$@"

   # shellcheck source=src/mulle-test-locate.sh
   . "${MULLE_TEST_LIBEXEC_DIR}/mulle-test-locate.sh"

   MULLE_TEST_DIR="${MULLE_TEST_DIR:-test}"
   test::locate::r_test_dir "${MULLE_TEST_DIR}"
   rval=$?

   if [ $rval -eq 1 ]
   then
      fail "Did not find a \"${MULLE_TEST_DIR}\" directory (${MULLE_USER_PWD})
${C_INFO}Initialize tests with:
${C_RESET_BOLD}   mulle-sde test init"
   fi

   r_absolutepath "${RVAL}"
   MULLE_TEST_DIR="${RVAL}"
   if [ -d "${MULLE_TEST_DIR}/.mulle/share/sde" -a \
       ! -d "${MULLE_TEST_DIR}/.mulle/share/test" ]
   then
      fail "\"${MULLE_TEST_DIR}\" is not a mulle-sde project marked for mulle-test"
   fi

   if [ "${PWD}" != "${MULLE_TEST_DIR}" ]
   then
      log_fluff "Going to test directory \"${MULLE_TEST_DIR}\" (${PWD#"${MULLE_USER_PWD}/"})"
      exekutor cd "${MULLE_TEST_DIR}" || exit 1
   fi

   return $rval
}


test::do_craft()
{
   log_entry "test::do_craft" "$@"

   local cmd

   if [ -x "./craft-test" ]
   then
      cmd="exekutor ./craft-test ${MULLE_TECHNICAL_FLAGS}"
   else
      if [ -x "./build-test" ]
      then
         cmd="exekutor ./build-test ${MULLE_TECHNICAL_FLAGS}"
      else
         if [ ! -d ".mulle/share/sde" ]
         then
            log_debug "No .mulle/share/sde folder and no build-test script, so don't run craft"
            return
         fi

         if [ "${MULLE_SDE_CRAFT_TARGET}" = 'NONE' ]
         then
            log_debug "MULLE_SDE_CRAFT_TARGET set to NONE, so nothing to do"
            return
         fi

         # shellcheck source=src/mulle-test-craft.sh
         . "${MULLE_TEST_LIBEXEC_DIR}/mulle-test-craft.sh"

         cmd="test::craft::main"
      fi
   fi

   eval `mulle-sde tool-env` || exit 1

   [ -z "${DEPENDENCY_DIR}" ] && _internal_fail "DEPENDENCY_DIR not set"
   [ -z "${KITCHEN_DIR}" ]    && _internal_fail "KITCHEN_DIR not set"

   log_verbose "Craft test dependencies"

   ${cmd} "$@"
}


test::r_escape_args()
{
  local arg

  RVAL=""
  for arg in "$@"
  do
     r_concat "${RVAL}" $(printf '%q' "${arg}")
  done
}



test::do_run()
{
   log_entry "test::do_run" "$@"

   local cmd

   log_verbose "Run tests"

   # legacy support :)
   if [ -x "./run-test" ]
   then
      cmd="./run-test ${MULLE_TECHNICAL_FLAGS}"
   else
      # shellcheck source=src/mulle-test-run.sh
      include "test::run"

      cmd="test::run::main"
   fi

   eval `mulle-sde tool-env` || exit 1

   [ -z "${DEPENDENCY_DIR}" ] && _internal_fail "DEPENDENCY_DIR not set"
   [ -z "${KITCHEN_DIR}" ]    && _internal_fail "KITCHEN_DIR not set"

   local environment

   if [ -z "${MULLE_TEST_EXECUTABLE}" ]
   then
      include "test::compiler"

      if test::compiler::r_env_sanitizer_flags "${SANITIZER}"
      then
         environment="${RVAL}"
      fi
   fi

   test::r_escape_args "$@"

   set -- ${environment} ${cmd} "${RVAL}"
   # Need this to be eval for the environment

   eval_exekutor "$@"
}


test::is_non_environment_commandline()
{
   while [ $# -ne 0 ]
   do
      case "$1" in
         -h|--help|help)
            return 0
         ;;

         --)
            break
         ;;

      esac
      shift
   done

   return 1
}


test::exec_in_subshell_if_needed()
{
   log_entry "test::exec_in_subshell_if_needed" "$@"

   if test::is_non_environment_commandline "$@"
   then
      return
   fi

   if [ "${MULLE_VIRTUAL_ROOT}" != "${PWD}" ]
   then
      if [ ! -z "${MULLE_TEST_DIR}" ]
      then
         exekutor cd "${MULLE_TEST_DIR}" || exit 1
      fi
      if [ -d "${PWD}/.mulle/share/env" ]
      then
         exekutor exec mulle-sde ${MULLE_TECHNICAL_FLAGS} \
                           exec mulle-test ${MULLE_TECHNICAL_FLAGS} "$@"
      else
         fail "Not a proper initialized test directory (${PWD#"${MULLE_USER_PWD}/"})
${C_INFO}To initialize for mulle-test:
${C_RESET_BOLD}   mulle-test init"
      fi
   else
      log_debug "Already in proper subshell ($MULLE_VIRTUAL_ROOT)"
   fi
}


test::get_quickstatus()
{
   log_entry "test::get_quickstatus" "$@"

   local rval

   rexekutor "${MULLE_CRAFT:-mulle-craft}" -s \
                  ${MULLE_TECHNICAL_FLAGS} \
               quickstatus
   rval=$?

   if [ $rval -eq 1 ]
   then
      exit 1
   fi

   return $rval
}


test::run_or_rerun()
{
   log_entry "test::run_or_rerun" "$@"

   local cmd="$1"; shift

   if ! test::get_quickstatus
   then
      # MEMO can't forward flags here for run or rerun
      test::do_craft || return 1
   fi

   if [ "${cmd}" = "rerun" ]
   then
      test::do_run --rerun "$@"
   else
      test::do_run "$@"
   fi
}


test::clean()
{
   log_entry "test::clean" "$@"

   local clean="$1"

   case "${clean}" in 
      'YES')
         local domains

         #
         # PROJECT_NAME is for old project, who don't have
         # TEST_PROJECT_NAME yet, of which there are many
         #
         domains="${MULLE_TEST_CLEAN_DOMAINS:-${TEST_PROJECT_NAME:-${PROJECT_NAME}}}"

         exekutor mulle-sde ${MULLE_TECHNICAL_FLAGS} \
                           clean --lenient "${domains}" || return $?
      ;;

      'ALL'|'TIDY'|'GRAVETIDY')
         r_lowercase "${clean}"
         exekutor mulle-sde ${MULLE_TECHNICAL_FLAGS} \
                        clean "${RVAL}" || return $?
      ;;
   esac
}


test::main()
{
   local FLAG_OUTSIDE_ENV="NO"       # need comment
   local MULLE_FLAG_DEFER="DEFAULT"
   local MULLE_TEST_DEFINE='YES'
   local OPTION_CLEAN='YES'
   local OPTION_CRAFT='DEFAULT'
   local OPTION_CONFIGURATION
   local SANITIZER

   #
   # On MacOS with the default Foundation/objc we can't
   # use the testallocator, because the singletons won't
   # get reclaimed
   #
   case "${MULLE_TEST_OBJC_DIALECT:-mulle-objc}" in
      mulle-objc)
         case "${MULLE_UNAME}" in
            darwin)
               SANITIZER="gmalloc:testallocator"
            ;;

            linux)
               SANITIZER="glibc:testallocator"
            ;;

            # mulle_atinit does not work on wimdows so we
            # can't reliably inject the testallocator
            'mingw'|'msys'|'windows')
               SANITIZER=""
            ;;

            *)
               SANITIZER="testallocator"
            ;;
         esac
      ;;

      *)
         case "${MULLE_UNAME}" in
            darwin)
               SANITIZER="gmalloc"
            ;;

            darwin)
               SANITIZER="glibc"
            ;;
         esac
      ;;
   esac

   #
   # simple option handling
   #
   while [ $# -ne 0 ]
   do
      if options_technical_flags "$1"
      then
         shift
         continue
      fi

      case "$1" in
         -h|--help|help)
            test::usage "${MULLE_TRACE}"
         ;;

         -f|--force)
            MULLE_FLAG_MAGNUM_FORCE="BOTH"
         ;;

         --debug)
            OPTION_CONFIGURATION="Debug"
         ;;

         --release)
            OPTION_CONFIGURATION="Release"
         ;;

         -d|--dir-name)
            [ $# -eq 1 ] && fail "Missing argument to \"$1\""
            shift

            MULLE_TEST_DIR="$1"
         ;;

         --gdb)
            r_colon_concat "${SANITIZER}" "gdb"
            SANITIZER="${RVAL}"
         ;;

         --clean-all)
            OPTION_CLEAN='ALL'
         ;;

         --no-clean)
            OPTION_CLEAN='NO'
         ;;

         --no-craft)
            OPTION_CRAFT='NO'
         ;;

         --valgrind)
            # no others beside  "valgrind"
            SANITIZER="valgrind"
         ;;

         --valgrind-no-leaks)
            # no others beside  "valgrind-no-leaks"
            SANITIZER="valgrind-no-leaks"
         ;;

         --coverage)
            r_colon_concat "${SANITIZER}" "coverage"
            SANITIZER="${RVAL}"
         ;;

         --objc-coverage)
            r_colon_concat "${SANITIZER}" "objc-coverage"
            SANITIZER="${RVAL}"
         ;;

         --sanitize-address)
            # no others beside  "address"
            SANITIZER="address"
         ;;

         --sanitize-undefined)
            # no others beside  "undefined"
            SANITIZER="undefined"
         ;;

         --sanitize-thread)
            # no others beside  "thread"
            SANITIZER="thread"
         ;;

         --testallocator)
            r_colon_remove "${SANITIZER}" "testallocator"
            r_colon_remove "${RVAL}" "zombie"
            r_colon_concat "${RVAL}" "testallocator"
            SANITIZER="${RVAL}"
         ;;

         --zombie)
            r_colon_remove "${SANITIZER}" "testallocator"
            r_colon_remove "${RVAL}" "zombie"
            r_colon_concat "${RVAL}" "zombie"
            SANITIZER="${RVAL}"
         ;;

         --add-sanitizer|--add-memory-checker)
            [ $# -eq 1 ] && fail "Missing argument to \"$1\""
            shift

            r_colon_concat "${SANITIZER}" "$1"
            SANITIZER="${RVAL}"
         ;;

         --no-mulle-test-define)
            MULLE_TEST_DEFINE='NO'
         ;;

         --no-sanitizer|--no-memory-checker)
            SANITIZER=
         ;;

         --version)
            printf "%s\n" "${MULLE_EXECUTABLE_VERSION}"
            exit 0
         ;;

         *)
            break
         ;;
      esac

      shift
   done

   options_setup_trace "${MULLE_TRACE}" && set -x

   MULLE_TEST_VAR_DIR="${MULLE_TEST_DIR:-${PWD}}/.mulle/var/${MULLE_HOSTNAME}/${MULLE_USERNAME}/test"

   log_setting "MULLE_VIRTUAL_ROOT=${MULLE_VIRTUAL_ROOT}"
   log_setting "MULLE_USER_PWD=${MULLE_USER_PWD}"
   log_setting "MULLE_TEST_VAR_DIR=${MULLE_TEST_VAR_DIR}"
   log_setting "SANITIZER=${SANITIZER}"

   #
   # this tells mulle-craft that everything is fine, though
   # .mulle/share/sde/mulle-sde is present, to prevent manual crafting
   # of tests, which is often undesirable
   #
   MULLE_TEST_ENVIRONMENT=YES
   export MULLE_TEST_ENVIRONMENT

   local cmd="$1"

   case "$cmd" in
      'arch')
         printf "%s\n" "${MULLE_ARCH}"
         exit 0
      ;;

      'version')
         printf "%s\n" "${MULLE_EXECUTABLE_VERSION}"
         exit 0
      ;;

      'uname')
         printf "%s\n" "${MULLE_UNAME}"
         exit 0
      ;;

      'libexec-dir')
         printf "%s\n" "${MULLE_TEST_LIBEXEC_DIR}"
         exit 0
      ;;

      "")
         cmd=run
         [ $# -ne 0 ] && shift
      ;;

      -*)
         cmd=run
      ;;

      *)
         case "${cmd}" in
            build|clean|cleanrun|coverage|craft|env|fetch|init|libexec-dir|linkorder|log\
|rebuild|recraft|rerun|run|retest|test-dir|version)
               shift
            ;;

            /*|.*)
               cmd='run'
            ;;

            *)
               if [ -e "${MULLE_USER_PWD}/${cmd}" ]
               then
                  cmd='run'
               else
                  shift
               fi
            ;;
         esac
      ;;
   esac

   case "${cmd}" in 
      'build')
         cmd="craft"
      ;;

      'recraft'|'rebuild')
         OPTION_CLEAN='ALL'
         cmd="craft"
      ;;

      'retest')
         OPTION_CLEAN='GRAVETIDY'
         cmd="run"
      ;;

      'recrun')
         OPTION_CLEAN='ALL'
         cmd="run"
      ;;

      'run'|'rerun')
         OPTION_CLEAN='NO'
      ;;

      # kinda useless ?
      'crun')
         OPTION_CLEAN='YES'
         cmd="run"
      ;;
   esac

   case "${cmd}" in
      craft)
         # bypass for --help
         if test::is_non_environment_commandline "$@"
         then
            include "test::craft"

            test::craft::main "$@"
            return
         fi

         if test::cd_test_dir
         then
            test::exec_in_subshell_if_needed "${cmd}" "$@"
         fi

         test::clean "${OPTION_CLEAN}"
         test::do_craft "$@" || return $?
      ;;

      run|rerun)
         # bypass for --help
         if test::is_non_environment_commandline "$@"
         then
            include "test::run"
            test::run::main "$@"
            return
         fi

         if test::cd_test_dir
         then
            test::exec_in_subshell_if_needed "${cmd}" "$@"
         fi

         test::clean "${OPTION_CLEAN}"

         if [ "${OPTION_CRAFT}" != 'NO' ]
         then
            test::do_craft || return $?
         fi
         test::run_or_rerun "${cmd}" "$@"
      ;;

      clean)
         if test::cd_test_dir
         then
            test::exec_in_subshell_if_needed "${cmd}" "$@"
         fi

         include "test::clean"

         test::clean::main "$@"
      ;;

      coverage)
         if test::cd_test_dir
         then
            test::exec_in_subshell_if_needed "${cmd}" "$@"
         fi

         include "test::coverage"

         test::coverage::main "$@"
      ;;

      craftorder)
         if test::cd_test_dir
         then
            test::exec_in_subshell_if_needed "${cmd}" "$@"
         fi

         exekutor mulle-sde ${MULLE_TECHNICAL_FLAGS} \
                           craftorder "$@"
      ;;

      env)
         rexekutor env | sort
      ;;


      fetch)
         if test::cd_test_dir
         then
            test::exec_in_subshell_if_needed "${cmd}" "$@"
         fi

         exekutor mulle-sde ${MULLE_TECHNICAL_FLAGS} \
                           fetch "$@" 
      ;;

      init)
         include "test::init"

         test::init::main "$@"
      ;;


      libexec-dir)
         printf "%s\n" "${MULLE_TEST_LIBEXEC_DIR}"
         exit 0
      ;;

      linkorder)
         if test::cd_test_dir
         then
            test::exec_in_subshell_if_needed "${cmd}" "$@"
         fi

         include "test::linkorder"

         test::linkorder::main "$@"
      ;;

      log)
         if test::cd_test_dir
         then
            test::exec_in_subshell_if_needed "${cmd}" "$@"
         fi

         exekutor mulle-sde ${MULLE_TECHNICAL_FLAGS} \
                           log "$@"
      ;;

      test-dir)
         # shellcheck source=src/mulle-test-locate.sh
         include "test::locate"

         test::locate::r_main "$@"
         printf "%s\n" "${RVAL}"
      ;;

      version)
         printf "%s\n" "${MULLE_EXECUTABLE_VERSION}"
         exit 0
      ;;

      *)
         log_error "Unknown command \"${cmd}\""
         test::usage "${MULLE_TRACE}"
      ;;
   esac
}


if [ -z "${MULLE_ARCH}" ]
then
   MULLE_ARCH="`gcc -v 2>&1  | sed -n -e '/Target:/s/.*: \([^-]*\)-.*/\1/p'`"
   MULLE_ARCH="${MULLE_ARCH:-`arch 2> /dev/null`}"
   MULLE_ARCH="${MULLE_ARCH:-x86_64}"
fi

call_with_flags "test::main" "${MULLE_TEST_FLAGS}" "$@"
